import { mkdirSync, writeFileSync, existsSync, readFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Add a line to `<dir>/.gitignore` if not already present. Preserves
 * existing entries (user hand-edits, earlier setup content); creates
 * the file if missing with a short header comment. Idempotent — safe
 * to call repeatedly for the same entry.
 */
function ensureGitignoreLine(dir: string, pattern: string): void {
  const path = join(dir, '.gitignore');
  if (!existsSync(path)) {
    writeFileSync(
      path,
      `# Generated artifacts — regenerated by cc-cli wtf / dispatch\n${pattern}\n`,
      'utf-8',
    );
    return;
  }
  const existing = readFileSync(path, 'utf-8');
  // Match exact-line presence — avoid false positives on substring matches
  const lines = existing.split(/\r?\n/);
  if (lines.some((l) => l.trim() === pattern)) return;
  const suffix = existing.endsWith('\n') ? '' : '\n';
  appendFileSync(path, `${suffix}${pattern}\n`, 'utf-8');
}
import { memberId as makeMemberId, channelId as makeChannelId, gatewayToken as makeGatewayToken } from './id.js';
import { writeConfig } from './parsers/config.js';
import type { Member } from './types/member.js';
import type { Channel } from './types/channel.js';
import type { AgentConfig } from './types/agent-config.js';
import type { GlobalConfig } from './types/global-config.js';
import { CHANNELS_JSON, MEMBERS_JSON, MESSAGES_JSONL } from './constants.js';
import { readConfig } from './parsers/config.js';
import { syncSkillsToAgent } from './skills.js';
import { CEO_BOOTSTRAP } from './templates/bootstrap-ceo.js';
import { buildAgentBootstrap } from './templates/bootstrap-agent.js';
import { getSharedTags } from './brain-culture.js';
import { readCulture } from './culture.js';
import { defaultIdentity as identityTemplate } from './templates/identity.js';
import { MEMORY_TEMPLATE } from './templates/memory.js';
import { USER_TEMPLATE } from './templates/user.js';
import { defaultEnvironment } from './templates/environment.js';
import { defaultHeartbeat as heartbeatTemplate } from './templates/heartbeat.js';
import { defaultRules as rulesTemplate } from './templates/rules.js';
import { buildThinClaudeMd } from './templates/claude-md.js';
import { buildHookSettings } from './templates/hook-settings.js';
import { inferKind } from './wtf-state.js';
import { createCasketIfMissing } from './casket.js';

export interface AgentSetupOpts {
  corpRoot: string;
  agentName: string;
  displayName: string;
  rank: Member['rank'];
  scope: Member['scope'];
  scopeId: string;
  spawnedBy: string;
  /** Explicit management supervisor. When set, persisted on the Member and used for hierarchy checks. */
  supervisorId?: string | null;
  model: string;
  provider: string;
  soulContent: string;
  agentsContent: string;
  heartbeatContent: string;
  identityContent?: string;
  userContent?: string;
  globalConfig: GlobalConfig;
  /** If true, skip creating .openclaw/ state dir (agent uses an external gateway) */
  remote?: boolean;
  /** Project name (resolved from scopeId) for project-scoped agents. */
  projectName?: string;
  /**
   * Registered harness name that executes this agent's turns. Persisted
   * in the agent's config.json and Member record. Optional; callers
   * typically resolve it from corp-level defaults before calling.
   */
  harness?: string;
  /**
   * Structural agent kind (Project 1.1). When omitted, resolveKind
   * infers from rank at read-time (pre-1.1 compat). New hires should
   * pass this explicitly so post-1.1 consumers read the structural
   * truth instead of the rank heuristic.
   */
  kind?: Member['kind'];
  /**
   * Role slot identifier (Project 1.1). References an entry in the
   * role registry. Optional for backwards-compat; pre-1.1 agents have
   * no role field and the registry lookup returns undefined when
   * needed, which callers handle gracefully.
   */
  role?: string;
}

export interface AgentSetupResult {
  member: Member;
  agentDir: string;
  config: AgentConfig;
}

export function setupAgentWorkspace(opts: AgentSetupOpts): AgentSetupResult {
  const {
    corpRoot,
    agentName,
    displayName,
    rank,
    scope,
    scopeId,
    spawnedBy,
    model,
    provider,
    soulContent,
    agentsContent,
    heartbeatContent,
    identityContent,
    userContent,
    globalConfig,
    remote,
  } = opts;

  // Project-scoped agents live at projects/<project>/agents/<name>/
  // Corp-scoped agents live at agents/<name>/
  const agentRelDir = scope === 'project' && opts.projectName
    ? `projects/${opts.projectName}/agents/${agentName}/`
    : `agents/${agentName}/`;
  const agentAbsDir = join(corpRoot, agentRelDir);
  const memberId = makeMemberId(displayName);
  const now = new Date().toISOString();

  // Effective kind for this setup. Post-1.1 callers pass opts.kind
  // explicitly; legacy call sites fall through to 'partner' (every
  // existing agent is persistent-named by profile, so the default
  // matches reality). This single value drives every kind-aware
  // branch in this function.
  const effectiveKind = opts.kind ?? 'partner';

  // Create workspace directories. skills/ is universal. brain/ is
  // Partner-only — Employees don't accumulate persistent memory at
  // the slot level (per-step handoff via WORKLOG; role-level pre-
  // BRAIN will be the shared memory surface when 4.x lands).
  if (effectiveKind === 'partner') {
    mkdirSync(join(agentAbsDir, 'brain'), { recursive: true });
  }
  mkdirSync(join(agentAbsDir, 'skills'), { recursive: true });

  // Sync corp-level skills to agent workspace
  try { syncSkillsToAgent(corpRoot, agentRelDir); } catch {}


  // Write workspace files. Filenames align with OpenClaw's recognized
  // bootstrap basename set (AGENTS.md, TOOLS.md) so OpenClaw auto-loads
  // them into the system prompt; Claude Code's CLAUDE.md @imports the
  // same names. The internal variable/template names keep "rules" and
  // "environment" for semantic clarity (these are rules + env info,
  // regardless of the AGENTS.md / TOOLS.md filesystem handle).
  const templateHarness = (opts.harness === 'claude-code' ? 'claude-code' : 'openclaw') as 'claude-code' | 'openclaw';

  // Kind-aware soul-file routing (Project 1.1). Partners get the full
  // soul-file stack; Employees skip SOUL / USER / MEMORY / IDENTITY
  // / BOOTSTRAP because at the slot level they don't have soul —
  // identity lives at the role level (role registry + pre-BRAIN when
  // 4.x lands). Shipping these files for Employees would be the
  // hollow-soul problem the refactor thesis explicitly rejects.
  //
  // When kind is undefined (legacy call sites), effectiveKind falls
  // back to 'partner' at the top of the function — the pre-1.1 shape
  // is preserved so round-trips through setupAgentWorkspace stay
  // idempotent for existing agents.
  if (effectiveKind === 'partner') {
    writeFileSync(join(agentAbsDir, 'SOUL.md'), soulContent, 'utf-8');
    writeFileSync(join(agentAbsDir, 'MEMORY.md'), MEMORY_TEMPLATE, 'utf-8');
    writeFileSync(join(agentAbsDir, 'IDENTITY.md'), identityContent ?? identityTemplate(displayName, rank), 'utf-8');
    writeFileSync(join(agentAbsDir, 'USER.md'), userContent ?? USER_TEMPLATE, 'utf-8');
  }
  // Always written — operational, not soul:
  writeFileSync(join(agentAbsDir, 'AGENTS.md'), agentsContent ?? rulesTemplate({ rank, harness: templateHarness }), 'utf-8');
  writeFileSync(join(agentAbsDir, 'HEARTBEAT.md'), heartbeatContent ?? heartbeatTemplate(rank), 'utf-8');
  writeFileSync(join(agentAbsDir, 'TOOLS.md'), defaultEnvironment({
    corpRoot,
    agentDir: agentAbsDir,
    projectName: opts.projectName,
    harness: templateHarness,
  }), 'utf-8');

  // STATUS.md + TASKS.md — workspace files the thin CLAUDE.md (0.7
  // shape) @imports. Without these stubs, fresh Claude Code hires would
  // log "import not found" warnings on every boot. Both start with a
  // minimal placeholder; agents rewrite STATUS.md themselves, and a
  // later task-watcher pass (or the agent's own tooling) renders
  // TASKS.md from open task chits.
  writeFileSync(
    join(agentAbsDir, 'STATUS.md'),
    `# Status\n\nNo current focus. Update this line with a one-sentence summary of what you're working on.\n`,
    'utf-8',
  );
  writeFileSync(
    join(agentAbsDir, 'TASKS.md'),
    `# Tasks\n\nNo tasks yet. This file is rendered from your open task chits — don't hand-edit.\nQuery directly with \`cc-cli task list --assigned ${agentName}\`.\n`,
    'utf-8',
  );

  // .gitignore — exclude CORP.md (generated fresh on every cc-cli wtf
  // call / OpenClaw dispatch; gitignored per the 0.7 spec because it's
  // a regenerated artifact, not hand-authored content). Without this,
  // every dispatch stages a new commit for the regenerated file.
  //
  // .claude/settings.json is NOT gitignored — it's deterministic from
  // (kind, agentSlug) via buildHookSettings, stable across rewires, and
  // needs to survive clones so Claude Code hooks work on a fresh checkout.
  //
  // Append-if-missing pattern (not blind overwrite): if a user already
  // has a .gitignore with their own entries, we add CORP.md to it
  // without destroying what's there.
  ensureGitignoreLine(agentAbsDir, 'CORP.md');

  // CLAUDE.md — only for agents on the claude-code harness. Project 0.7
  // architecture: thin survival-anchor shell, no @import of AGENTS.md or
  // TOOLS.md. The corp manual + situational context come dynamically
  // via `cc-cli wtf` fired by the SessionStart / PreCompact hooks
  // configured in .claude/settings.json (written below).
  //
  // OpenClaw agents skip CLAUDE.md — the OpenClaw harness will prepend
  // wtf output at dispatch time instead (same content, different trigger).
  // That harness integration lands in a follow-up PR; for now OpenClaw
  // agents still boot via the legacy fragments pipeline.
  //
  // AGENTS.md + TOOLS.md writes above remain unchanged — their files
  // still get created on disk for backward compatibility with system
  // agents composed via buildCeoAgents + defaultRules that haven't been
  // migrated yet. The thin CLAUDE.md simply doesn't @import them, so
  // they're stale-but-harmless until 0.7.5 rewire cleans them up on
  // existing workspaces.
  if (templateHarness === 'claude-code') {
    const kind = inferKind(rank);
    const corpName = corpRoot.split(/[/\\]/).pop() ?? 'corp';
    writeFileSync(
      join(agentAbsDir, 'CLAUDE.md'),
      buildThinClaudeMd({
        kind,
        displayName,
        role: rank,
        corpName,
        workspacePath: agentAbsDir,
      }),
      'utf-8',
    );

    // .claude/settings.json — hook wiring. SessionStart + Stop for
    // both kinds; PreCompact + UserPromptSubmit for Partners only.
    // Until 0.7.3 ships `cc-cli audit`, the Stop hook command will
    // fail to find the subcommand and exit non-zero — but Claude
    // Code hooks tolerate missing commands (they log + continue), so
    // this is safe to ship ahead of 0.7.3.
    const claudeDir = join(agentAbsDir, '.claude');
    mkdirSync(claudeDir, { recursive: true });
    const settings = buildHookSettings({ kind, agentSlug: agentName });
    writeFileSync(
      join(claudeDir, 'settings.json'),
      JSON.stringify(settings, null, 2) + '\n',
      'utf-8',
    );
  }
  // BOOTSTRAP.md — first-run absorption shield. Partners only (Project
  // 1.1): Employees are ephemeral role-slots, they don't have a "first
  // run" to be shielded into. The bootstrap file exists to help a NEW
  // Partner absorb corp vocabulary + culture before they have to
  // respond to anything — a one-time gift, not load-bearing after that
  // (agents delete it themselves when onboarding completes). Employees
  // arrive already-scoped by role; they boot into work immediately.
  //
  // CEO gets the founding conversation guide; hired Partners get the
  // absorption shield with culture vocabulary injected when available.
  if (effectiveKind === 'partner') {
    let bootstrapContent = CEO_BOOTSTRAP;
    if (rank !== 'master') {
      let sharedTags: string[] = [];
      try {
        sharedTags = getSharedTags(corpRoot).map(t => t.tag);
      } catch { /* culture data unavailable — fine, bootstrap works without it */ }

      // Resolve hiring agent's display name from members.json
      let hiringAgentName: string | undefined;
      if (opts.spawnedBy) {
        try {
          const allMembers = readConfig<Array<{ id: string; displayName: string }>>(join(corpRoot, MEMBERS_JSON));
          const spawner = allMembers.find(m => m.id === opts.spawnedBy);
          if (spawner) hiringAgentName = spawner.displayName;
        } catch { /* name resolution failed — fine, bootstrap works without it */ }
      }

      let hasCulture = false;
      try {
        hasCulture = readCulture(corpRoot) !== null;
      } catch { /* fine, bootstrap works without it */ }

      bootstrapContent = buildAgentBootstrap({
        sharedTags: sharedTags.length > 0 ? sharedTags : undefined,
        hiringAgentName,
        hasCulture,
      });
    }
    writeFileSync(join(agentAbsDir, 'BOOTSTRAP.md'), bootstrapContent, 'utf-8');
  }

  // Agent config
  const agentConfig: AgentConfig = {
    memberId,
    displayName,
    model,
    provider,
    port: null,
    scope,
    scopeId,
    ...(opts.harness ? { harness: opts.harness } : {}),
  };
  writeConfig(join(agentAbsDir, 'config.json'), agentConfig);

  // OpenClaw state directory (only for locally-spawned agents, not remote)
  if (!remote) {
    const openclawStateDir = join(agentAbsDir, '.openclaw');
    mkdirSync(join(openclawStateDir, 'agents', 'main', 'agent'), { recursive: true });

    // Generate a unique gateway token for this agent
    const gatewayToken = makeGatewayToken();

    // openclaw.json
    const openclawConfig = {
      auth: {
        profiles: {
          [`${provider}:default`]: {
            provider,
            mode: 'token',
          },
        },
      },
      agents: {
        defaults: {
          model: { primary: `${provider}/${model}` },
          workspace: agentAbsDir.replace(/\\/g, '/'),
          compaction: { mode: 'safeguard' },
          verboseDefault: 'full',
          blockStreamingDefault: 'off',
        },
      },
      gateway: {
        mode: 'local',
        bind: 'loopback',
        auth: { mode: 'token', token: gatewayToken },
        http: {
          endpoints: {
            chatCompletions: { enabled: true },
          },
        },
      },
    };
    writeConfig(join(openclawStateDir, 'openclaw.json'), openclawConfig);

    // auth-profiles.json — inject API key from global config
    const apiKey = globalConfig.apiKeys[provider as keyof typeof globalConfig.apiKeys];
    const authProfiles = {
      version: 1,
      profiles: {
        [`${provider}:default`]: {
          type: 'token',
          provider,
          token: apiKey ?? '',
        },
      },
    };
    writeConfig(
      join(openclawStateDir, 'agents', 'main', 'agent', 'auth-profiles.json'),
      authProfiles,
    );
  }

  // Member entry. Kind + role are written when the caller passed them
  // explicitly; absence means pre-1.1 call site (e.g. legacy hire path
  // that hasn't migrated yet) or intentional "infer later" semantics.
  // resolveKind() at read-time handles missing kind via rank fallback.
  const member: Member = {
    id: memberId,
    displayName,
    rank,
    status: 'active',
    type: 'agent',
    scope,
    scopeId,
    agentDir: agentRelDir,
    port: null,
    spawnedBy,
    ...(opts.supervisorId ? { supervisorId: opts.supervisorId } : {}),
    createdAt: now,
    ...(opts.harness ? { harness: opts.harness } : {}),
    ...(opts.kind ? { kind: opts.kind } : {}),
    ...(opts.role ? { role: opts.role } : {}),
  };

  // Casket chit — the durable work-pointer read by `cc-cli wtf` (0.7.1)
  // and `cc-cli audit` (0.7.3). Idempotent; tolerates re-hire paths
  // that call setupAgentWorkspace against an existing workspace.
  // createdBy = the agent's own member id: Casket is agent-owned state,
  // which keeps git attribution legible when a Casket is later advanced
  // by the chain walker or by hand-complete.
  //
  // Non-fatal on error. The workspace is already fully established at
  // this point; missing Casket degrades to "audit gate fails open for
  // this agent" rather than crashing the hire flow outright. The wtf
  // output + first audit run will surface the gap if it ever happens.
  try {
    createCasketIfMissing(corpRoot, agentName, memberId);
  } catch {
    /* non-fatal — logged by the eventual first audit pass */
  }

  return { member, agentDir: agentRelDir, config: agentConfig };
}

export function createDmChannel(
  corpRoot: string,
  member1Id: string,
  member2Id: string,
  member1Name: string,
  member2Name: string,
): Channel {
  const names = [member1Name, member2Name].sort();
  const channelName = `dm-${names[0]}-${names[1]}`;
  const channelPath = `channels/${channelName}/`;
  const now = new Date().toISOString();

  // Create channel directory
  mkdirSync(join(corpRoot, channelPath), { recursive: true });
  writeFileSync(join(corpRoot, channelPath, MESSAGES_JSONL), '', 'utf-8');

  const channel: Channel = {
    id: makeChannelId(channelName),
    name: channelName,
    kind: 'direct',
    scope: 'corp',
    scopeId: '',
    teamId: null,
    memberIds: [member1Id, member2Id],
    createdBy: member1Id,
    path: channelPath,
    createdAt: now,
  };

  return channel;
}

export function addMemberToRegistry(corpRoot: string, member: Member): void {
  const membersPath = join(corpRoot, MEMBERS_JSON);
  const members = readConfig<Member[]>(membersPath);
  members.push(member);
  writeConfig(membersPath, members);
}

export function addChannelToRegistry(corpRoot: string, channel: Channel): void {
  const channelsPath = join(corpRoot, CHANNELS_JSON);
  const channels = readConfig<Channel[]>(channelsPath);
  channels.push(channel);
  writeConfig(channelsPath, channels);
}

export function addMemberToChannel(corpRoot: string, channelId: string, memberId: string): void {
  const channelsPath = join(corpRoot, CHANNELS_JSON);
  const channels = readConfig<Channel[]>(channelsPath);
  const ch = channels.find((c) => c.id === channelId);
  if (ch && !ch.memberIds.includes(memberId)) {
    ch.memberIds.push(memberId);
    writeConfig(channelsPath, channels);
  }
}

// All workspace file templates are now in shared/src/templates/
